// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0O2DQI2kkKTJw_oZobY3eBQiDCmr9ATk',
    appId: '1:872989141595:web:0602ea74243a78ef942d7e',
    messagingSenderId: '872989141595',
    projectId: 'wsporte-cup-premium',
    authDomain: 'wsporte-cup-premium.firebaseapp.com',
    storageBucket: 'wsporte-cup-premium.firebasestorage.app',
    measurementId: 'G-NT3T8N73C1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfP4EYgbfp00nokTzPxvxLxwcmAHr_AeM',
    appId: '1:872989141595:android:4b7a3dad81eba7f9942d7e',
    messagingSenderId: '872989141595',
    projectId: 'wsporte-cup-premium',
    storageBucket: 'wsporte-cup-premium.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfDYHA3918kNuwrfYrsYDDRW7xORCK858',
    appId: '1:872989141595:ios:b1e0459f6e92aa29942d7e',
    messagingSenderId: '872989141595',
    projectId: 'wsporte-cup-premium',
    storageBucket: 'wsporte-cup-premium.firebasestorage.app',
    iosBundleId: 'br.com.william.wsportsCupPremium',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAfDYHA3918kNuwrfYrsYDDRW7xORCK858',
    appId: '1:872989141595:ios:b1e0459f6e92aa29942d7e',
    messagingSenderId: '872989141595',
    projectId: 'wsporte-cup-premium',
    storageBucket: 'wsporte-cup-premium.firebasestorage.app',
    iosBundleId: 'br.com.william.wsportsCupPremium',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA0O2DQI2kkKTJw_oZobY3eBQiDCmr9ATk',
    appId: '1:872989141595:web:58974dde717b618f942d7e',
    messagingSenderId: '872989141595',
    projectId: 'wsporte-cup-premium',
    authDomain: 'wsporte-cup-premium.firebaseapp.com',
    storageBucket: 'wsporte-cup-premium.firebasestorage.app',
    measurementId: 'G-SEQMZP9B21',
  );

}