import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
// 1. Importações obrigatórias do Firebase
import 'package:firebase_core/firebase_core.dart';
import 'core/widgets/update_banner.dart';
import 'firebase_options.dart';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:wsports_cup_premium/features/splash/presentation/pages/video_splash_screen.dart';
import 'package:wsports_cup_premium/features/world_cup/presentation/bloc/world_cup_bloc.dart';
import 'package:wsports_cup_premium/features/world_cup/presentation/bloc/world_cup_event.dart';
import 'package:wsports_cup_premium/injection_container.dart';
import 'package:wsports_cup_premium/injection_container.dart' as di;
import './core/services/ad_service.dart';
import 'core/constants/app_theme.dart';

void main() async {
  // 1. Inicialização do Flutter
  WidgetsFlutterBinding.ensureInitialized();

  // 2. A MÁGICA ACONTECE AQUI: Inicializa o Firebase apontando para o seu banco
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);

  // 3. Inicialização da Injeção de Dependência (agora segura, pois o Firebase já acordou)
  await di.init();
  // 4. Inicializa o AdMob em background para NÃO travar o seu Splash Screen
  AdService.initialize().catchError((e) => debugPrint('Erro AdMob: $e'));
  // 1. Descomente esta linha para rodar o insert, depois comente novamente!
  //await popularGruposFirebase(); ////////////////////////////EENVIAR DADOS PARA O BANCO FIREBASE (RODAR APENAS UMA VEZ, DEPOIS COMENTAR NOVAMENTE)
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return BlocProvider<WorldCupBloc>(
      create: (context) => sl<WorldCupBloc>()..add(LoadMatchesEvent()),
      child: MaterialApp(
        title: 'Copa do Mundo 2026',
        debugShowCheckedModeBanner: false,

        // Aplica o Tema Premium
        theme: AppTheme.darkTheme,
        // Envelopa toda a navegação do app dentro do UpdateBanner
        // CORREÇÃO: Envelopa toda a navegação com verificação de segurança (Null Safety)
        builder: (context, child) {
          if (child == null) {
            return const SizedBox.shrink(); // Proteção: Se for nulo, desenha nada temporariamente
          }
          return UpdateBanner(child: child);
        },

        // Injeta o Bloco da Copa e carrega os jogos
        home: const VideoSplashScreen(),
      ),
    );
  }
}

Future<void> popularGruposFirebase() async {
  final firestore = FirebaseFirestore.instance;
  final collection = firestore.collection('matches');

  // Tabela Oficial - Primeira Rodada dos 12 Grupos
  final jogos = [
    // === GRUPO A ===
    {
      'id': 'gA_1',
      'group': 'GRUPO A',
      'homeTeam': 'México',
      'homeFlag': 'https://flagcdn.com/w320/mx.png',
      'awayTeam': 'África do Sul',
      'awayFlag': 'https://flagcdn.com/w320/za.png',
      'date': DateTime(2026, 6, 11, 16, 0),
      'stadium': 'Estádio Azteca',
      'country': 'México',
      'location': 'Cidade do México',
      'status': 'Agendado',
    },
    {
      'id': 'gA_2',
      'group': 'GRUPO A',
      'homeTeam': 'Coreia do Sul',
      'homeFlag': 'https://flagcdn.com/w320/kr.png',
      'awayTeam': 'Vencedor Rep D',
      'awayFlag':
          'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b7/Flag_of_Europe.svg/320px-Flag_of_Europe.svg.png',
      'date': DateTime(2026, 6, 11, 23, 0),
      'stadium': 'Akron Estádio',
      'country': 'México',
      'location': 'Zapopan',
      'status': 'Agendado',
    },
    {
      'id': 'gA_3',
      'group': 'GRUPO A',
      'homeTeam': 'Vencedor Rep D',
      'homeFlag':
          'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b7/Flag_of_Europe.svg/320px-Flag_of_Europe.svg.png',
      'awayTeam': 'África do Sul',
      'awayFlag': 'https://flagcdn.com/w320/za.png',
      'date': DateTime(2026, 6, 18, 13, 0),
      'stadium': 'Mercedes-Benz Estádio',
      'country': 'Estados Unidos',
      'location': 'Atlanta',
      'status': 'Agendado',
    },
    {
      'id': 'gA_4',
      'group': 'GRUPO A',
      'homeTeam': 'México',
      'homeFlag': 'https://flagcdn.com/w320/mx.png',
      'awayTeam': 'Coreia do Sul',
      'awayFlag': 'https://flagcdn.com/w320/kr.png',
      'date': DateTime(2026, 6, 18, 22, 0),
      'stadium': 'Akron Estádio',
      'country': 'México',
      'location': 'Zapopan',
      'status': 'Agendado',
    },
    {
      'id': 'gA_5',
      'group': 'GRUPO A',
      'homeTeam': 'África do Sul',
      'homeFlag': 'https://flagcdn.com/w320/za.png',
      'awayTeam': 'Coreia do Sul',
      'awayFlag': 'https://flagcdn.com/w320/kr.png',
      'date': DateTime(2026, 6, 24, 22, 0),
      'stadium': 'BBVA Estádio',
      'country': 'México',
      'location': 'Guadalupe',
      'status': 'Agendado',
    },
    {
      'id': 'gA_6',
      'group': 'GRUPO A',
      'homeTeam': 'Vencedor Rep D',
      'homeFlag':
          'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b7/Flag_of_Europe.svg/320px-Flag_of_Europe.svg.png',
      'awayTeam': 'México',
      'awayFlag': 'https://flagcdn.com/w320/mx.png',
      'date': DateTime(2026, 6, 24, 22, 0),
      'stadium': 'Banorte Estádio',
      'country': 'México',
      'location': 'Cidade do México',
      'status': 'Agendado',
    },
    // === GRUPO B ===
    {
      'id': 'gB_1',
      'group': 'GRUPO B',
      'homeTeam': 'Canada',
      'homeFlag': 'https://flagcdn.com/w320/ca.png',
      'awayTeam': 'Vencedor Rep A',
      'awayFlag':
          'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b7/Flag_of_Europe.svg/320px-Flag_of_Europe.svg.png',
      'date': DateTime(2026, 6, 12, 16, 0),
      'stadium': 'BMO Field',
      'country': 'Canadá',
      'location': 'Toronto',
      'status': 'Agendado',
    },
    {
      'id': 'gB_2',
      'group': 'GRUPO B',
      'homeTeam': 'Catar',
      'homeFlag': 'https://flagcdn.com/w320/qa.png',
      'awayTeam': 'Suiça',
      'awayFlag': 'https://flagcdn.com/w320/ch.png',
      'date': DateTime(2026, 6, 13, 16, 0),
      'stadium': 'Levi\'s Estádio',
      'country': 'Estados Unidos',
      'location': 'California',
      'status': 'Agendado',
    },
    {
      'id': 'gB_3',
      'group': 'GRUPO B',
      'homeTeam': 'Suiça',
      'homeFlag': 'https://flagcdn.com/w320/ch.png',
      'awayTeam': 'Vencedor Rep A',
      'awayFlag':
          'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b7/Flag_of_Europe.svg/320px-Flag_of_Europe.svg.png',
      'date': DateTime(2026, 6, 18, 16, 0),
      'stadium': 'SoFI Estádio',
      'country': 'Estados Unidos',
      'location': 'Inglewood',
      'status': 'Agendado',
    },
    {
      'id': 'gB_4',
      'group': 'GRUPO B',
      'homeTeam': 'Canada',
      'homeFlag': 'https://flagcdn.com/w320/ca.png',
      'awayTeam': 'Catar',
      'awayFlag': 'https://flagcdn.com/w320/qa.png',
      'date': DateTime(2026, 6, 18, 19, 0),
      'stadium': 'BC Place Estádio',
      'country': 'Canadá',
      'location': 'Vancouver',
      'status': 'Agendado',
    },
    {
      'id': 'gB_5',
      'group': 'GRUPO B',
      'homeTeam': 'Suiça',
      'homeFlag': 'https://flagcdn.com/w320/ch.png',
      'awayTeam': 'Canada',
      'awayFlag': 'https://flagcdn.com/w320/ca.png',
      'date': DateTime(2026, 6, 24, 16, 0),
      'stadium': 'BC Place Estádio',
      'country': 'Canadá',
      'location': 'Vancouver',
      'status': 'Agendado',
    },
    {
      'id': 'gB_6',
      'group': 'GRUPO B',
      'homeTeam': 'Vencedor Rep A',
      'homeFlag':
          'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b7/Flag_of_Europe.svg/320px-Flag_of_Europe.svg.png',
      'awayTeam': 'Catar',
      'awayFlag': 'https://flagcdn.com/w320/qa.png',
      'date': DateTime(2026, 6, 24, 16, 0),
      'stadium': 'Lumen Field',
      'country': 'Estados Unidos',
      'location': 'Seattle',
      'status': 'Agendado',
    },
    // === GRUPO C (Brasil) ===
    {
      'id': 'gC_1',
      'group': 'GRUPO C',
      'homeTeam': 'Brasil',
      'homeFlag': 'https://flagcdn.com/w320/br.png',
      'awayTeam': 'Marrocos',
      'awayFlag': 'https://flagcdn.com/w320/ma.png',
      'date': DateTime(2026, 6, 13, 16, 0),
      'stadium': 'MetLife Estádio',
      'country': 'Estados Unidos',
      'location': 'Nova York',
      'status': 'Agendado',
    },
    {
      'id': 'gC_2',
      'group': 'GRUPO C',
      'homeTeam': 'Haiti',
      'homeFlag': 'https://flagcdn.com/w320/ht.png',
      'awayTeam': 'Escócia',
      'awayFlag': 'https://flagcdn.com/w320/gb-sct.png',
      'date': DateTime(2026, 6, 13, 22, 0),
      'stadium': 'Gillette Estádio',
      'country': 'Estados Unidos',
      'location': 'New York',
      'status': 'Agendado',
    },
    {
      'id': 'gC_3',
      'group': 'GRUPO C',
      'homeTeam': 'Escócia',
      'homeFlag': 'https://flagcdn.com/w320/gb-sct.png',
      'awayTeam': 'Marrocos',
      'awayFlag': 'https://flagcdn.com/w320/ma.png',
      'date': DateTime(2026, 6, 19, 19, 0),
      'stadium': 'Gillette Estádio',
      'country': 'Estados Unidos',
      'location': 'New York',
      'status': 'Agendado',
    },
    {
      'id': 'gC_4',
      'group': 'GRUPO C',
      'homeTeam': 'Brasil',
      'homeFlag': 'https://flagcdn.com/w320/br.png',
      'awayTeam': 'Haiti',
      'awayFlag': 'https://flagcdn.com/w320/ht.png',
      'date': DateTime(2026, 6, 19, 22, 0),
      'stadium': 'Lincoln Financial Field',
      'country': 'Estados Unidos',
      'location': 'filadélfia',
      'status': 'Agendado',
    },
    {
      'id': 'gC_5',
      'group': 'GRUPO C',
      'homeTeam': 'Marrocos',
      'homeFlag': 'https://flagcdn.com/w320/ma.png',
      'awayTeam': 'Haiti',
      'awayFlag': 'https://flagcdn.com/w320/ht.png',
      'date': DateTime(2026, 6, 24, 19, 0),
      'stadium': 'Mercedes-Benz Estádio',
      'country': 'Estados Unidos',
      'location': 'Atlanta',
      'status': 'Agendado',
    },
    {
      'id': 'gC_6',
      'group': 'GRUPO C',
      'homeTeam': 'Escócia',
      'homeFlag': 'https://flagcdn.com/w320/gb-sct.png',
      'awayTeam': 'Brasil',
      'awayFlag': 'https://flagcdn.com/w320/br.png',
      'date': DateTime(2026, 6, 24, 19, 0),
      'stadium': 'Hard Rock Estádio',
      'country': 'Estados Unidos',
      'location': 'Miami',
      'status': 'Agendado',
    },

    // === GRUPO D ===
    {
      'id': 'gD_1',
      'group': 'GRUPO D',
      'homeTeam': 'Estados Unidos',
      'homeFlag': 'https://flagcdn.com/w320/us.png',
      'awayTeam': 'Paraguai',
      'awayFlag': 'https://flagcdn.com/w320/py.png',
      'date': DateTime(2026, 6, 12, 22, 0),
      'stadium': 'SoFi Estádio',
      'country': 'Estados Unidos',
      'location': 'Inglewood',
      'status': 'Agendado',
    },
    {
      'id': 'gD_2',
      'group': 'GRUPO D',
      'homeTeam': 'Austrália',
      'homeFlag': 'https://flagcdn.com/w320/au.png',
      'awayTeam': 'Vencedor Rep C',
      'awayFlag':
          'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b7/Flag_of_Europe.svg/320px-Flag_of_Europe.svg.png',
      'date': DateTime(2026, 6, 14, 01, 0),
      'stadium': 'BC Place Estádio',
      'country': 'Canadá',
      'location': 'Vancouver',
      'status': 'Agendado',
    },
    {
      'id': 'gD_3',
      'group': 'GRUPO D',
      'homeTeam': 'Estados Unidos',
      'homeFlag': 'https://flagcdn.com/w320/us.png',
      'awayTeam': 'Austrália',
      'awayFlag': 'https://flagcdn.com/w320/au.png',
      'date': DateTime(2026, 6, 19, 16, 0),
      'stadium': 'Lumen Field',
      'country': 'Estados Unidos',
      'location': 'Seattle',
      'status': 'Agendado',
    },
    {
      'id': 'gD_4',
      'group': 'GRUPO D',
      'homeTeam': 'Vencedor Rep C',
      'homeFlag':
          'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b7/Flag_of_Europe.svg/320px-Flag_of_Europe.svg.png',
      'awayTeam': 'Paraguai',
      'awayFlag': 'https://flagcdn.com/w320/py.png',
      'date': DateTime(2026, 6, 20, 01, 0),
      'stadium': 'Levi\'s Estádio',
      'country': 'Estados Unidos',
      'location': 'California',
      'status': 'Agendado',
    },
    {
      'id': 'gD_5',
      'group': 'GRUPO D',
      'homeTeam': 'Vencedor Rep C',
      'homeFlag':
          'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b7/Flag_of_Europe.svg/320px-Flag_of_Europe.svg.png',
      'awayTeam': 'Estados Unidos',
      'awayFlag': 'https://flagcdn.com/w320/us.png',
      'date': DateTime(2026, 6, 25, 23, 0),
      'stadium': 'SoFi Estádio',
      'country': 'Estados Unidos',
      'location': 'Inglewood',
      'status': 'Agendado',
    },
    {
      'id': 'gD_6',
      'group': 'GRUPO D',
      'homeTeam': 'Paraguai',
      'homeFlag': 'https://flagcdn.com/w320/py.png',
      'awayTeam': 'Austrália',
      'awayFlag': 'https://flagcdn.com/w320/au.png',
      'date': DateTime(2026, 6, 25, 23, 0),
      'stadium': 'Levi\'s Estádio',
      'country': 'Estados Unidos',
      'location': 'California',
      'status': 'Agendado',
    },
    // === GRUPO E ===
    {
      'id': 'gE_1',
      'group': 'GRUPO E',
      'homeTeam': 'Alemanha',
      'homeFlag': 'https://flagcdn.com/w320/de.png',
      'awayTeam': 'Curaçao',
      'awayFlag': 'https://flagcdn.com/w320/cw.png',
      'date': DateTime(2026, 6, 14, 14, 0),
      'stadium': 'NRG Estádio',
      'country': 'Estados Unidos',
      'location': 'Houston',
      'status': 'Agendado',
    },
    {
      'id': 'gE_2',
      'group': 'GRUPO E',
      'homeTeam': 'Costa do Marfim',
      'homeFlag': 'https://flagcdn.com/w320/ci.png',
      'awayTeam': 'Equador',
      'awayFlag': 'https://flagcdn.com/w320/ec.png',
      'date': DateTime(2026, 6, 15, 20, 0),
      'stadium': 'Lincoln Financial Field',
      'country': 'Estados Unidos',
      'location': 'Filadélfia',
      'status': 'Agendado',
    },
    {
      'id': 'gE_3',
      'group': 'GRUPO E',
      'homeTeam': 'Alemanha',
      'homeFlag': 'https://flagcdn.com/w320/de.png',
      'awayTeam': 'Costa do Marfim',
      'awayFlag': 'https://flagcdn.com/w320/ci.png',
      'date': DateTime(2026, 6, 20, 17, 0),
      'stadium': 'BMO Field',
      'country': 'Canadá',
      'location': 'Toronto',
      'status': 'Agendado',
    },
    {
      'id': 'gE_4',
      'group': 'GRUPO E',
      'homeTeam': 'Equador',
      'homeFlag': 'https://flagcdn.com/w320/ec.png',
      'awayTeam': 'Curaçao',
      'awayFlag': 'https://flagcdn.com/w320/cw.png',
      'date': DateTime(2026, 6, 20, 21, 0),
      'stadium': 'Arrowhead Estádio',
      'country': 'Estados Unidos',
      'location': 'Kansas City',
      'status': 'Agendado',
    },
    {
      'id': 'gE_5',
      'group': 'GRUPO E',
      'homeTeam': 'Curaçao',
      'homeFlag': 'https://flagcdn.com/w320/cw.png',
      'awayTeam': 'Costa do Marfim',
      'awayFlag': 'https://flagcdn.com/w320/ci.png',
      'date': DateTime(2026, 6, 25, 17, 0),
      'stadium': 'Lincoln Financial Field',
      'country': 'Estados Unidos',
      'location': 'Filadélfia',
      'status': 'Agendado',
    },
    {
      'id': 'gE_6',
      'group': 'GRUPO E',
      'homeTeam': 'Equador',
      'homeFlag': 'https://flagcdn.com/w320/ec.png',
      'awayTeam': 'Alemanha',
      'awayFlag': 'https://flagcdn.com/w320/de.png',
      'date': DateTime(2026, 6, 25, 17, 0),
      'stadium': 'MetLife Estádio',
      'country': 'Estados Unidos',
      'location': 'Nova York',
      'status': 'Agendado',
    },

    // === GRUPO F ===
    {
      'id': 'gF_1',
      'group': 'GRUPO F',
      'homeTeam': 'Holanda',
      'homeFlag': 'https://flagcdn.com/w320/nl.png',
      'awayTeam': 'Japão',
      'awayFlag': 'https://flagcdn.com/w320/jp.png',
      'date': DateTime(2026, 6, 16, 17, 0),
      'stadium': 'AT&T Estádio',
      'country': 'Estados Unidos',
      'location': 'Arlington',
      'status': 'Agendado',
    },
    {
      'id': 'gF_2',
      'group': 'GRUPO F',
      'homeTeam': 'Vencedor Rep B',
      'homeFlag':
          'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b7/Flag_of_Europe.svg/320px-Flag_of_Europe.svg.png',
      'awayTeam': 'Tunísia',
      'awayFlag': 'https://flagcdn.com/w320/tn.png',
      'date': DateTime(2026, 6, 14, 23, 0),
      'stadium': 'Estádio BBVA',
      'country': 'México',
      'location': 'Guadalupe',
      'status': 'Agendado',
    },
    {
      'id': 'gF_3',
      'group': 'GRUPO F',
      'homeTeam': 'Holanda',
      'homeFlag': 'https://flagcdn.com/w320/nl.png',
      'awayTeam': 'Vencedor Rep B',
      'awayFlag':
          'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b7/Flag_of_Europe.svg/320px-Flag_of_Europe.svg.png',
      'date': DateTime(2026, 6, 20, 14, 0),
      'stadium': 'NRG Estádio',
      'country': 'Estados Unidos',
      'location': 'Houston',
      'status': 'Agendado',
    },
    {
      'id': 'gF_4',
      'group': 'GRUPO F',
      'homeTeam': 'Tunísia',
      'homeFlag': 'https://flagcdn.com/w320/tn.png',
      'awayTeam': 'Japão',
      'awayFlag': 'https://flagcdn.com/w320/jp.png',
      'date': DateTime(2026, 6, 21, 01, 0),
      'stadium': 'BBVA Estádio',
      'country': 'México',
      'location': 'Guadalupe',
      'status': 'Agendado',
    },
    {
      'id': 'gF_5',
      'group': 'GRUPO F',
      'homeTeam': 'Tunísia',
      'homeFlag': 'https://flagcdn.com/w320/tn.png',
      'awayTeam': 'Holanda',
      'awayFlag': 'https://flagcdn.com/w320/nl.png',
      'date': DateTime(2026, 6, 25, 20, 0),
      'stadium': 'Arrowhead Estádio',
      'country': 'Estados Unidos',
      'location': 'Kansas City',
      'status': 'Agendado',
    },
    {
      'id': 'gF_6',
      'group': 'GRUPO F',
      'homeTeam': 'Japão',
      'homeFlag': 'https://flagcdn.com/w320/jp.png',
      'awayTeam': 'Vencedor Rep B',
      'awayFlag':
          'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b7/Flag_of_Europe.svg/320px-Flag_of_Europe.svg.png',
      'date': DateTime(2026, 6, 25, 20, 0),
      'stadium': 'AT&T Estádio',
      'country': 'Estados Unidos',
      'location': 'Arlington',
      'status': 'Agendado',
    },

    // === GRUPO G ===
    {
      'id': 'gG_1',
      'group': 'GRUPO G',
      'homeTeam': 'Bélgica',
      'homeFlag': 'https://flagcdn.com/w320/be.png',
      'awayTeam': 'Egito',
      'awayFlag': 'https://flagcdn.com/w320/eg.png',
      'date': DateTime(2026, 6, 15, 16, 0),
      'stadium': 'Estádio Lumen Field',
      'country': 'Estados Unidos',
      'location': 'Seattle',
      'status': 'Agendado',
    },
    {
      'id': 'gG_2',
      'group': 'GRUPO G',
      'homeTeam': 'Irã',
      'homeFlag': 'https://flagcdn.com/w320/ir.png',
      'awayTeam': 'Nova Zelândia',
      'awayFlag': 'https://flagcdn.com/w320/nz.png',
      'date': DateTime(2026, 6, 15, 22, 0),
      'stadium': 'SoFi Estádio',
      'country': 'Estados Unidos',
      'location': 'Inglewood',
      'status': 'Agendado',
    },
    {
      'id': 'gG_3',
      'group': 'GRUPO G',
      'homeTeam': 'Bélgica',
      'homeFlag': 'https://flagcdn.com/w320/be.png',
      'awayTeam': 'Irã',
      'awayFlag': 'https://flagcdn.com/w320/ir.png',
      'date': DateTime(2026, 6, 21, 16, 0),
      'stadium': 'SoFi Estádio',
      'country': 'Estados Unidos',
      'location': 'Inglewood',
      'status': 'Agendado',
    },
    {
      'id': 'gG_4',
      'group': 'GRUPO G',
      'homeTeam': 'Nova Zelândia',
      'homeFlag': 'https://flagcdn.com/w320/nz.png',
      'awayTeam': 'Egito',
      'awayFlag': 'https://flagcdn.com/w320/eg.png',
      'date': DateTime(2026, 6, 21, 22, 0),
      'stadium': 'BC Place Estádio',
      'country': 'Canadá',
      'location': 'Vancouver',
      'status': 'Agendado',
    },
    {
      'id': 'gG_5',
      'group': 'GRUPO G',
      'homeTeam': 'Nova Zelândia',
      'homeFlag': 'https://flagcdn.com/w320/nz.png',
      'awayTeam': 'Bélgica',
      'awayFlag': 'https://flagcdn.com/w320/be.png',
      'date': DateTime(2026, 6, 27, 00, 0),
      'stadium': 'BC Place Estádio',
      'country': 'Canadá',
      'location': 'Vancouver',
      'status': 'Agendado',
    },
    {
      'id': 'gG_6',
      'group': 'GRUPO G',
      'homeTeam': 'Egito',
      'homeFlag': 'https://flagcdn.com/w320/eg.png',
      'awayTeam': 'Irã',
      'awayFlag': 'https://flagcdn.com/w320/ir.png',
      'date': DateTime(2026, 6, 27, 00, 0),
      'stadium': 'Lumen Field',
      'country': 'Estados Unidos',
      'location': 'Seattle',
      'status': 'Agendado',
    },

    // === GRUPO H ===
    {
      'id': 'gH_1',
      'group': 'GRUPO H',
      'homeTeam': 'Espanha',
      'homeFlag': 'https://flagcdn.com/w320/es.png',
      'awayTeam': 'Cabo Verde',
      'awayFlag': 'https://flagcdn.com/w320/cv.png',
      'date': DateTime(2026, 6, 15, 13, 0),
      'stadium': 'Estádio Mercedes-Benz',
      'country': 'Estados Unidos',
      'location': 'Atlanta',
      'status': 'Agendado',
    },
    {
      'id': 'gH_2',
      'group': 'GRUPO H',
      'homeTeam': 'Arabia Saudita',
      'homeFlag': 'https://flagcdn.com/w320/sa.png',
      'awayTeam': 'Uruguai',
      'awayFlag': 'https://flagcdn.com/w320/uy.png',
      'date': DateTime(2026, 6, 15, 19, 0),
      'stadium': 'Hard ROCK STADIUM',
      'country': 'Estados Unidos',
      'location': 'Miami',
      'status': 'Agendado',
    },
    {
      'id': 'gH_3',
      'group': 'GRUPO H',
      'homeTeam': 'Espanha',
      'homeFlag': 'https://flagcdn.com/w320/es.png',
      'awayTeam': 'Arabia Saudita',
      'awayFlag': 'https://flagcdn.com/w320/sa.png',
      'date': DateTime(2026, 6, 21, 13, 0),
      'stadium': 'Mercedes-Benz Estádio',
      'country': 'Estados Unidos',
      'location': 'Atlanta',
      'status': 'Agendado',
    },
    {
      'id': 'gH_4',
      'group': 'GRUPO H',
      'homeTeam': 'Uruguai',
      'homeFlag': 'https://flagcdn.com/w320/uy.png',
      'awayTeam': 'Cabo Verde',
      'awayFlag': 'https://flagcdn.com/w320/cv.png',
      'date': DateTime(2026, 6, 21, 19, 0),
      'stadium': 'Hard Rock Estádio',
      'country': 'Estados Unidos',
      'location': 'Miami',
      'status': 'Agendado',
    },
    {
      'id': 'gH_5',
      'group': 'GRUPO H',
      'homeTeam': 'Cabo Verde',
      'homeFlag': 'https://flagcdn.com/w320/cv.png',
      'awayTeam': 'Arabia Saudita',
      'awayFlag': 'https://flagcdn.com/w320/sa.png',
      'date': DateTime(2026, 6, 26, 21, 0),
      'stadium': 'NRG Estádio',
      'country': 'Estados Unidos',
      'location': 'Houston',
      'status': 'Agendado',
    },
    {
      'id': 'gH_6',
      'group': 'GRUPO H',
      'homeTeam': 'Uruguai',
      'homeFlag': 'https://flagcdn.com/w320/uy.png',
      'awayTeam': 'Espanha',
      'awayFlag': 'https://flagcdn.com/w320/es.png',
      'date': DateTime(2026, 6, 26, 21, 0),
      'stadium': 'Akron Estádio',
      'country': 'México',
      'location': 'Zapopan',
      'status': 'Agendado',
    },

    // === GRUPO I ===
    {
      'id': 'gI_1',
      'group': 'GRUPO I',
      'homeTeam': 'França',
      'homeFlag': 'https://flagcdn.com/w320/fr.png',
      'awayTeam': 'Senegal',
      'awayFlag': 'https://flagcdn.com/w320/sn.png',
      'date': DateTime(2026, 6, 16, 16, 0),
      'stadium': 'MetLife Estádio',
      'country': 'Estados Unidos',
      'location': 'Nova York',
      'status': 'Agendado',
    },
    {
      'id': 'gI_2',
      'group': 'GRUPO I',
      'homeTeam': 'Vencedor Rep 2',
      'homeFlag':
          'https://upload.wikimedia.org/wikipedia/commons/thumb/e/ef/International_Flag_of_Planet_Earth.svg/320px-International_Flag_of_Planet_Earth.svg.png',
      'awayTeam': 'Noruega',
      'awayFlag': 'https://flagcdn.com/w320/no.png',
      'date': DateTime(2026, 6, 16, 19, 0),
      'stadium': 'Gillette Estádio',
      'country': 'Estados Unidos',
      'location': 'New York',
      'status': 'Agendado',
    },
    {
      'id': 'gI_3',
      'group': 'GRUPO I',
      'homeTeam': 'França',
      'homeFlag': 'https://flagcdn.com/w320/fr.png',
      'awayTeam': 'Vencedor Rep 2',
      'awayFlag':
          'https://upload.wikimedia.org/wikipedia/commons/thumb/e/ef/International_Flag_of_Planet_Earth.svg/320px-International_Flag_of_Planet_Earth.svg.png',
      'date': DateTime(2026, 6, 22, 18, 0),
      'stadium': 'Lincoln Financial Field',
      'country': 'Estados Unidos',
      'location': 'Filadélfia',
      'status': 'Agendado',
    },
    {
      'id': 'gI_4',
      'group': 'GRUPO I',
      'homeTeam': 'Noruega',
      'homeFlag': 'https://flagcdn.com/w320/no.png',
      'awayTeam': 'Senegal',
      'awayFlag': 'https://flagcdn.com/w320/sn.png',
      'date': DateTime(2026, 6, 22, 21, 0),
      'stadium': 'MetLife Estádio',
      'country': 'Estados Unidos',
      'location': 'Nova York',
      'status': 'Agendado',
    },
    {
      'id': 'gI_5',
      'group': 'GRUPO I',
      'homeTeam': 'Noruega',
      'homeFlag': 'https://flagcdn.com/w320/no.png',
      'awayTeam': 'França',
      'awayFlag': 'https://flagcdn.com/w320/fr.png',
      'date': DateTime(2026, 6, 26, 16, 0),
      'stadium': 'Gillette Estádio',
      'country': 'Estados Unidos',
      'location': 'Nova York',
      'status': 'Agendado',
    },
    {
      'id': 'gI_6',
      'group': 'GRUPO I',
      'homeTeam': 'Senegal',
      'homeFlag': 'https://flagcdn.com/w320/sn.png',
      'awayTeam': 'Vencedor Rep 2',
      'awayFlag':
          'https://upload.wikimedia.org/wikipedia/commons/thumb/e/ef/International_Flag_of_Planet_Earth.svg/320px-International_Flag_of_Planet_Earth.svg.png',
      'date': DateTime(2026, 6, 26, 16, 0),
      'stadium': 'BMO Field',
      'country': 'Canadá',
      'location': 'Toronto',
      'status': 'Agendado',
    },

    // === GRUPO J ===
    {
      'id': 'gJ_1',
      'group': 'GRUPO J',
      'homeTeam': 'Argentina',
      'homeFlag': 'https://flagcdn.com/w320/ar.png',
      'awayTeam': 'Argélia',
      'awayFlag': 'https://flagcdn.com/w320/dz.png',
      'date': DateTime(2026, 6, 16, 22, 0),
      'stadium': 'Estádio Arrowhead',
      'country': 'Estados Unidos',
      'location': 'Kansas City',
      'status': 'Agendado',
    },
    {
      'id': 'gJ_2',
      'group': 'GRUPO J',
      'homeTeam': 'Áustria',
      'homeFlag': 'https://flagcdn.com/w320/at.png',
      'awayTeam': 'Jordânia',
      'awayFlag': 'https://flagcdn.com/w320/jo.png',
      'date': DateTime(2026, 6, 17, 01, 0),
      'stadium': 'Levi\'s Estádio',
      'country': 'Estados Unidos',
      'location': 'California',
      'status': 'Agendado',
    },
    {
      'id': 'gJ_3',
      'group': 'GRUPO J',
      'homeTeam': 'Argentina',
      'homeFlag': 'https://flagcdn.com/w320/ar.png',
      'awayTeam': 'Áustria',
      'awayFlag': 'https://flagcdn.com/w320/at.png',
      'date': DateTime(2026, 6, 22, 14, 0),
      'stadium': 'AT&T Estádio',
      'country': 'Estados Unidos',
      'location': 'Arlington',
      'status': 'Agendado',
    },
    {
      'id': 'gJ_4',
      'group': 'GRUPO J',
      'homeTeam': 'Jordânia',
      'homeFlag': 'https://flagcdn.com/w320/jo.png',
      'awayTeam': 'Argélia',
      'awayFlag': 'https://flagcdn.com/w320/dz.png',
      'date': DateTime(2026, 6, 23, 00, 0),
      'stadium': 'Levi\'s Estádio',
      'country': 'Estados Unidos',
      'location': 'California',
      'status': 'Agendado',
    },
    {
      'id': 'gJ_5',
      'group': 'GRUPO J',
      'homeTeam': 'Argélia',
      'homeFlag': 'https://flagcdn.com/w320/dz.png',
      'awayTeam': 'Áustria',
      'awayFlag': 'https://flagcdn.com/w320/at.png',
      'date': DateTime(2026, 6, 27, 23, 0),
      'stadium': 'Estádio Arrowhead',
      'country': 'Estados Unidos',
      'location': 'Kansas City',
      'status': 'Agendado',
    },
    {
      'id': 'gJ_6',
      'group': 'GRUPO J',
      'homeTeam': 'Jordânia',
      'homeFlag': 'https://flagcdn.com/w320/jo.png',
      'awayTeam': 'Argentina',
      'awayFlag': 'https://flagcdn.com/w320/ar.png',
      'date': DateTime(2026, 6, 27, 23, 0),
      'stadium': 'AT&T Estádio',
      'country': 'Estados Unidos',
      'location': 'Arlington',
      'status': 'Agendado',
    },

    // === GRUPO K ===
    {
      'id': 'gK_1',
      'group': 'GRUPO K',
      'homeTeam': 'Portugal',
      'homeFlag': 'https://flagcdn.com/w320/pt.png',
      'awayTeam': 'Vencedor Rep 1',
      'awayFlag':
          'https://upload.wikimedia.org/wikipedia/commons/thumb/e/ef/International_Flag_of_Planet_Earth.svg/320px-International_Flag_of_Planet_Earth.svg.png',
      'date': DateTime(2026, 6, 17, 14, 0),
      'stadium': 'NRG Estádio',
      'country': 'Estados Unidos',
      'location': 'Houston',
      'status': 'Agendado',
    },
    {
      'id': 'gK_2',
      'group': 'GRUPO K',
      'homeTeam': 'Uzbequistão',
      'homeFlag': 'https://flagcdn.com/w320/uz.png',
      'awayTeam': 'Colombia',
      'awayFlag': 'https://flagcdn.com/w320/co.png',
      'date': DateTime(2026, 6, 17, 23, 0),
      'stadium': 'Banorte Estádio',
      'country': 'México',
      'location': 'Cidade de México',
      'status': 'Agendado',
    },
    {
      'id': 'gK_3',
      'group': 'GRUPO K',
      'homeTeam': 'Portugal',
      'homeFlag': 'https://flagcdn.com/w320/pt.png',
      'awayTeam': 'Uzbequistão',
      'awayFlag': 'https://flagcdn.com/w320/uz.png',
      'date': DateTime(2026, 6, 23, 14, 0),
      'stadium': 'NRG Estádio',
      'country': 'Estados Unidos',
      'location': 'Houston',
      'status': 'Agendado',
    },
    {
      'id': 'gK_4',
      'group': 'GRUPO K',
      'homeTeam': 'Colombia',
      'homeFlag': 'https://flagcdn.com/w320/co.png',
      'awayTeam': 'Vencedor Rep 1',
      'awayFlag':
          'https://upload.wikimedia.org/wikipedia/commons/thumb/e/ef/International_Flag_of_Planet_Earth.svg/320px-International_Flag_of_Planet_Earth.svg.png',
      'date': DateTime(2026, 6, 23, 23, 0),
      'stadium': 'Akron Estádio',
      'country': 'México',
      'location': 'Zapopan',
      'status': 'Agendado',
    },
    {
      'id': 'gK_5',
      'group': 'GRUPO K',
      'homeTeam': 'Colombia',
      'homeFlag': 'https://flagcdn.com/w320/co.png',
      'awayTeam': 'Portugal',
      'awayFlag': 'https://flagcdn.com/w320/pt.png',
      'date': DateTime(2026, 6, 27, 20, 30),
      'stadium': 'Hard Rock Estádio',
      'country': 'Estados Unidos',
      'location': 'Miami',
      'status': 'Agendado',
    },
    {
      'id': 'gK_6',
      'group': 'GRUPO K',
      'homeTeam': 'Vencedor Rep 1',
      'homeFlag':
          'https://upload.wikimedia.org/wikipedia/commons/thumb/e/ef/International_Flag_of_Planet_Earth.svg/320px-International_Flag_of_Planet_Earth.svg.png',
      'awayTeam': 'Uzbequistão',
      'awayFlag': 'https://flagcdn.com/w320/uz.png',
      'date': DateTime(2026, 6, 27, 20, 30),
      'stadium': 'Mercedes-Benz Estádio',
      'country': 'Estados Unidos',
      'location': 'Atlanta',
      'status': 'Agendado',
    },
    // === GRUPO L ===
    {
      'id': 'gL_1',
      'group': 'GRUPO L',
      'homeTeam': 'Inglaterra',
      'homeFlag': 'https://flagcdn.com/w320/gb-eng.png',
      'awayTeam': 'Croácia',
      'awayFlag': 'https://flagcdn.com/w320/hr.png',
      'date': DateTime(2026, 6, 17, 17, 0),
      'stadium': 'AT&T Estádio',
      'country': 'Estados Unidos',
      'location': 'Arlington',
      'status': 'Agendado',
    },
    {
      'id': 'gL_2',
      'group': 'GRUPO L',
      'homeTeam': 'Gana',
      'homeFlag': 'https://flagcdn.com/w320/gh.png',
      'awayTeam': 'Panamá',
      'awayFlag': 'https://flagcdn.com/w320/pa.png',
      'date': DateTime(2026, 6, 17, 20, 0),
      'stadium': 'BMO Field',
      'country': 'Canadá',
      'location': 'Toronto',
      'status': 'Agendado',
    },
    {
      'id': 'gL_3',
      'group': 'GRUPO L',
      'homeTeam': 'Inglaterra',
      'homeFlag': 'https://flagcdn.com/w320/gb-eng.png',
      'awayTeam': 'Gana',
      'awayFlag': 'https://flagcdn.com/w320/gh.png',
      'date': DateTime(2026, 6, 23, 17, 0),
      'stadium': 'Gillette Estádio',
      'country': 'Estados Unidos',
      'location': 'New York',
      'status': 'Agendado',
    },
    {
      'id': 'gL_4',
      'group': 'GRUPO L',
      'homeTeam': 'Panamá',
      'homeFlag': 'https://flagcdn.com/w320/pa.png',
      'awayTeam': 'Croácia',
      'awayFlag': 'https://flagcdn.com/w320/hr.png',
      'date': DateTime(2026, 6, 23, 20, 0),
      'stadium': 'BMO Field',
      'country': 'Canadá',
      'location': 'Toronto',
      'status': 'Agendado',
    },
    {
      'id': 'gL_5',
      'group': 'GRUPO L',
      'homeTeam': 'Panamá',
      'homeFlag': 'https://flagcdn.com/w320/pa.png',
      'awayTeam': 'Inglaterra',
      'awayFlag': 'https://flagcdn.com/w320/gb-eng.png',
      'date': DateTime(2026, 6, 27, 18, 0),
      'stadium': 'MetLife Estádio',
      'country': 'Estados Unidos',
      'location': 'Nova York',
      'status': 'Agendado',
    },
    {
      'id': 'gL_6',
      'group': 'GRUPO L',
      'homeTeam': 'Croácia',
      'homeFlag': 'https://flagcdn.com/w320/hr.png',
      'awayTeam': 'Gana',
      'awayFlag': 'https://flagcdn.com/w320/gh.png',
      'date': DateTime(2026, 6, 27, 18, 0),
      'stadium': 'Lincoln Financial Field',
      'country': 'Estados Unidos',
      'location': 'Filadélfia',
      'status': 'Agendado',
    },
    // ==========================================
    // === MATA-MATA: 32-AVOS DE FINAL (16 jogos) ===
    // ==========================================
    {
      'id': 'r32_1',
      'group': 'R32',
      'homeTeam': 'A Definir',
      'homeFlag':
          'https://upload.wikimedia.org/wikipedia/commons/thumb/a/ad/Placeholder_no_text.svg/150px-Placeholder_no_text.svg.png',
      'awayTeam': 'A Definir',
      'awayFlag':
          'https://upload.wikimedia.org/wikipedia/commons/thumb/a/ad/Placeholder_no_text.svg/150px-Placeholder_no_text.svg.png',
      'date': DateTime(2026, 6, 28, 13, 0),
      'stadium': 'A Definir',
      'country': 'A Definir',
      'location': 'A Definir',
      'status': 'Agendado',
    },
    {
      'id': 'r32_2',
      'group': 'R32',
      'homeTeam': 'A Definir',
      'homeFlag':
          'https://upload.wikimedia.org/wikipedia/commons/thumb/a/ad/Placeholder_no_text.svg/150px-Placeholder_no_text.svg.png',
      'awayTeam': 'A Definir',
      'awayFlag':
          'https://upload.wikimedia.org/wikipedia/commons/thumb/a/ad/Placeholder_no_text.svg/150px-Placeholder_no_text.svg.png',
      'date': DateTime(2026, 6, 28, 17, 0),
      'stadium': 'A Definir',
      'country': 'A Definir',
      'location': 'A Definir',
      'status': 'Agendado',
    },
    {
      'id': 'r32_3',
      'group': 'R32',
      'homeTeam': 'A Definir',
      'homeFlag':
          'https://upload.wikimedia.org/wikipedia/commons/thumb/a/ad/Placeholder_no_text.svg/150px-Placeholder_no_text.svg.png',
      'awayTeam': 'A Definir',
      'awayFlag':
          'https://upload.wikimedia.org/wikipedia/commons/thumb/a/ad/Placeholder_no_text.svg/150px-Placeholder_no_text.svg.png',
      'date': DateTime(2026, 6, 29, 13, 0),
      'stadium': 'A Definir',
      'country': 'A Definir',
      'location': 'A Definir',
      'status': 'Agendado',
    },
    {
      'id': 'r32_4',
      'group': 'R32',
      'homeTeam': 'A Definir',
      'homeFlag':
          'https://upload.wikimedia.org/wikipedia/commons/thumb/a/ad/Placeholder_no_text.svg/150px-Placeholder_no_text.svg.png',
      'awayTeam': 'A Definir',
      'awayFlag':
          'https://upload.wikimedia.org/wikipedia/commons/thumb/a/ad/Placeholder_no_text.svg/150px-Placeholder_no_text.svg.png',
      'date': DateTime(2026, 6, 29, 17, 0),
      'stadium': 'A Definir',
      'country': 'A Definir',
      'location': 'A Definir',
      'status': 'Agendado',
    },
    {
      'id': 'r32_5',
      'group': 'R32',
      'homeTeam': 'A Definir',
      'homeFlag':
          'https://upload.wikimedia.org/wikipedia/commons/thumb/a/ad/Placeholder_no_text.svg/150px-Placeholder_no_text.svg.png',
      'awayTeam': 'A Definir',
      'awayFlag':
          'https://upload.wikimedia.org/wikipedia/commons/thumb/a/ad/Placeholder_no_text.svg/150px-Placeholder_no_text.svg.png',
      'date': DateTime(2026, 6, 30, 13, 0),
      'stadium': 'A Definir',
      'country': 'A Definir',
      'location': 'A Definir',
      'status': 'Agendado',
    },
    {
      'id': 'r32_6',
      'group': 'R32',
      'homeTeam': 'A Definir',
      'homeFlag':
          'https://upload.wikimedia.org/wikipedia/commons/thumb/a/ad/Placeholder_no_text.svg/150px-Placeholder_no_text.svg.png',
      'awayTeam': 'A Definir',
      'awayFlag':
          'https://upload.wikimedia.org/wikipedia/commons/thumb/a/ad/Placeholder_no_text.svg/150px-Placeholder_no_text.svg.png',
      'date': DateTime(2026, 6, 30, 17, 0),
      'stadium': 'A Definir',
      'country': 'A Definir',
      'location': 'A Definir',
      'status': 'Agendado',
    },
    {
      'id': 'r32_7',
      'group': 'R32',
      'homeTeam': 'A Definir',
      'homeFlag':
          'https://upload.wikimedia.org/wikipedia/commons/thumb/a/ad/Placeholder_no_text.svg/150px-Placeholder_no_text.svg.png',
      'awayTeam': 'A Definir',
      'awayFlag':
          'https://upload.wikimedia.org/wikipedia/commons/thumb/a/ad/Placeholder_no_text.svg/150px-Placeholder_no_text.svg.png',
      'date': DateTime(2026, 7, 1, 13, 0),
      'stadium': 'A Definir',
      'country': 'A Definir',
      'location': 'A Definir',
      'status': 'Agendado',
    },
    {
      'id': 'r32_8',
      'group': 'R32',
      'homeTeam': 'A Definir',
      'homeFlag':
          'https://upload.wikimedia.org/wikipedia/commons/thumb/a/ad/Placeholder_no_text.svg/150px-Placeholder_no_text.svg.png',
      'awayTeam': 'A Definir',
      'awayFlag':
          'https://upload.wikimedia.org/wikipedia/commons/thumb/a/ad/Placeholder_no_text.svg/150px-Placeholder_no_text.svg.png',
      'date': DateTime(2026, 7, 1, 17, 0),
      'stadium': 'A Definir',
      'country': 'A Definir',
      'location': 'A Definir',
      'status': 'Agendado',
    },
    {
      'id': 'r32_9',
      'group': 'R32',
      'homeTeam': 'A Definir',
      'homeFlag':
          'https://upload.wikimedia.org/wikipedia/commons/thumb/a/ad/Placeholder_no_text.svg/150px-Placeholder_no_text.svg.png',
      'awayTeam': 'A Definir',
      'awayFlag':
          'https://upload.wikimedia.org/wikipedia/commons/thumb/a/ad/Placeholder_no_text.svg/150px-Placeholder_no_text.svg.png',
      'date': DateTime(2026, 7, 2, 13, 0),
      'stadium': 'A Definir',
      'country': 'A Definir',
      'location': 'A Definir',
      'status': 'Agendado',
    },
    {
      'id': 'r32_10',
      'group': 'R32',
      'homeTeam': 'A Definir',
      'homeFlag':
          'https://upload.wikimedia.org/wikipedia/commons/thumb/a/ad/Placeholder_no_text.svg/150px-Placeholder_no_text.svg.png',
      'awayTeam': 'A Definir',
      'awayFlag':
          'https://upload.wikimedia.org/wikipedia/commons/thumb/a/ad/Placeholder_no_text.svg/150px-Placeholder_no_text.svg.png',
      'date': DateTime(2026, 7, 2, 17, 0),
      'stadium': 'A Definir',
      'country': 'A Definir',
      'location': 'A Definir',
      'status': 'Agendado',
    },
    {
      'id': 'r32_11',
      'group': 'R32',
      'homeTeam': 'A Definir',
      'homeFlag':
          'https://upload.wikimedia.org/wikipedia/commons/thumb/a/ad/Placeholder_no_text.svg/150px-Placeholder_no_text.svg.png',
      'awayTeam': 'A Definir',
      'awayFlag':
          'https://upload.wikimedia.org/wikipedia/commons/thumb/a/ad/Placeholder_no_text.svg/150px-Placeholder_no_text.svg.png',
      'date': DateTime(2026, 7, 2, 21, 0),
      'stadium': 'A Definir',
      'country': 'A Definir',
      'location': 'A Definir',
      'status': 'Agendado',
    },
    {
      'id': 'r32_12',
      'group': 'R32',
      'homeTeam': 'A Definir',
      'homeFlag':
          'https://upload.wikimedia.org/wikipedia/commons/thumb/a/ad/Placeholder_no_text.svg/150px-Placeholder_no_text.svg.png',
      'awayTeam': 'A Definir',
      'awayFlag':
          'https://upload.wikimedia.org/wikipedia/commons/thumb/a/ad/Placeholder_no_text.svg/150px-Placeholder_no_text.svg.png',
      'date': DateTime(2026, 7, 3, 13, 0),
      'stadium': 'A Definir',
      'country': 'A Definir',
      'location': 'A Definir',
      'status': 'Agendado',
    },
    {
      'id': 'r32_13',
      'group': 'R32',
      'homeTeam': 'A Definir',
      'homeFlag':
          'https://upload.wikimedia.org/wikipedia/commons/thumb/a/ad/Placeholder_no_text.svg/150px-Placeholder_no_text.svg.png',
      'awayTeam': 'A Definir',
      'awayFlag':
          'https://upload.wikimedia.org/wikipedia/commons/thumb/a/ad/Placeholder_no_text.svg/150px-Placeholder_no_text.svg.png',
      'date': DateTime(2026, 7, 3, 17, 0),
      'stadium': 'A Definir',
      'country': 'A Definir',
      'location': 'A Definir',
      'status': 'Agendado',
    },
    {
      'id': 'r32_14',
      'group': 'R32',
      'homeTeam': 'A Definir',
      'homeFlag':
          'https://upload.wikimedia.org/wikipedia/commons/thumb/a/ad/Placeholder_no_text.svg/150px-Placeholder_no_text.svg.png',
      'awayTeam': 'A Definir',
      'awayFlag':
          'https://upload.wikimedia.org/wikipedia/commons/thumb/a/ad/Placeholder_no_text.svg/150px-Placeholder_no_text.svg.png',
      'date': DateTime(2026, 7, 3, 21, 0),
      'stadium': 'A Definir',
      'country': 'A Definir',
      'location': 'A Definir',
      'status': 'Agendado',
    },
    {
      'id': 'r32_15',
      'group': 'R32',
      'homeTeam': 'A Definir',
      'homeFlag':
          'https://upload.wikimedia.org/wikipedia/commons/thumb/a/ad/Placeholder_no_text.svg/150px-Placeholder_no_text.svg.png',
      'awayTeam': 'A Definir',
      'awayFlag':
          'https://upload.wikimedia.org/wikipedia/commons/thumb/a/ad/Placeholder_no_text.svg/150px-Placeholder_no_text.svg.png',
      'date': DateTime(2026, 7, 3, 22, 0),
      'stadium': 'A Definir',
      'country': 'A Definir',
      'location': 'A Definir',
      'status': 'Agendado',
    },
    {
      'id': 'r32_16',
      'group': 'R32',
      'homeTeam': 'A Definir',
      'homeFlag':
          'https://upload.wikimedia.org/wikipedia/commons/thumb/a/ad/Placeholder_no_text.svg/150px-Placeholder_no_text.svg.png',
      'awayTeam': 'A Definir',
      'awayFlag':
          'https://upload.wikimedia.org/wikipedia/commons/thumb/a/ad/Placeholder_no_text.svg/150px-Placeholder_no_text.svg.png',
      'date': DateTime(2026, 7, 3, 23, 0),
      'stadium': 'A Definir',
      'country': 'A Definir',
      'location': 'A Definir',
      'status': 'Agendado',
    },

    // ==========================================
    // === MATA-MATA: OITAVAS DE FINAL (8 jogos) ===
    // ==========================================
    {
      'id': 'r16_1',
      'group': 'R16',
      'homeTeam': 'Vencedor R32',
      'homeFlag':
          'https://upload.wikimedia.org/wikipedia/commons/thumb/a/ad/Placeholder_no_text.svg/150px-Placeholder_no_text.svg.png',
      'awayTeam': 'Vencedor R32',
      'awayFlag':
          'https://upload.wikimedia.org/wikipedia/commons/thumb/a/ad/Placeholder_no_text.svg/150px-Placeholder_no_text.svg.png',
      'date': DateTime(2026, 7, 4, 13, 0),
      'stadium': 'A Definir',
      'country': 'A Definir',
      'location': 'A Definir',
      'status': 'Agendado',
    },
    {
      'id': 'r16_2',
      'group': 'R16',
      'homeTeam': 'Vencedor R32',
      'homeFlag':
          'https://upload.wikimedia.org/wikipedia/commons/thumb/a/ad/Placeholder_no_text.svg/150px-Placeholder_no_text.svg.png',
      'awayTeam': 'Vencedor R32',
      'awayFlag':
          'https://upload.wikimedia.org/wikipedia/commons/thumb/a/ad/Placeholder_no_text.svg/150px-Placeholder_no_text.svg.png',
      'date': DateTime(2026, 7, 4, 17, 0),
      'stadium': 'A Definir',
      'country': 'A Definir',
      'location': 'A Definir',
      'status': 'Agendado',
    },
    {
      'id': 'r16_3',
      'group': 'R16',
      'homeTeam': 'Vencedor R32',
      'homeFlag':
          'https://upload.wikimedia.org/wikipedia/commons/thumb/a/ad/Placeholder_no_text.svg/150px-Placeholder_no_text.svg.png',
      'awayTeam': 'Vencedor R32',
      'awayFlag':
          'https://upload.wikimedia.org/wikipedia/commons/thumb/a/ad/Placeholder_no_text.svg/150px-Placeholder_no_text.svg.png',
      'date': DateTime(2026, 7, 5, 13, 0),
      'stadium': 'A Definir',
      'country': 'A Definir',
      'location': 'A Definir',
      'status': 'Agendado',
    },
    {
      'id': 'r16_4',
      'group': 'R16',
      'homeTeam': 'Vencedor R32',
      'homeFlag':
          'https://upload.wikimedia.org/wikipedia/commons/thumb/a/ad/Placeholder_no_text.svg/150px-Placeholder_no_text.svg.png',
      'awayTeam': 'Vencedor R32',
      'awayFlag':
          'https://upload.wikimedia.org/wikipedia/commons/thumb/a/ad/Placeholder_no_text.svg/150px-Placeholder_no_text.svg.png',
      'date': DateTime(2026, 7, 5, 17, 0),
      'stadium': 'A Definir',
      'country': 'A Definir',
      'location': 'A Definir',
      'status': 'Agendado',
    },
    {
      'id': 'r16_5',
      'group': 'R16',
      'homeTeam': 'Vencedor R32',
      'homeFlag':
          'https://upload.wikimedia.org/wikipedia/commons/thumb/a/ad/Placeholder_no_text.svg/150px-Placeholder_no_text.svg.png',
      'awayTeam': 'Vencedor R32',
      'awayFlag':
          'https://upload.wikimedia.org/wikipedia/commons/thumb/a/ad/Placeholder_no_text.svg/150px-Placeholder_no_text.svg.png',
      'date': DateTime(2026, 7, 6, 13, 0),
      'stadium': 'A Definir',
      'country': 'A Definir',
      'location': 'A Definir',
      'status': 'Agendado',
    },
    {
      'id': 'r16_6',
      'group': 'R16',
      'homeTeam': 'Vencedor R32',
      'homeFlag':
          'https://upload.wikimedia.org/wikipedia/commons/thumb/a/ad/Placeholder_no_text.svg/150px-Placeholder_no_text.svg.png',
      'awayTeam': 'Vencedor R32',
      'awayFlag':
          'https://upload.wikimedia.org/wikipedia/commons/thumb/a/ad/Placeholder_no_text.svg/150px-Placeholder_no_text.svg.png',
      'date': DateTime(2026, 7, 6, 17, 0),
      'stadium': 'A Definir',
      'country': 'A Definir',
      'location': 'A Definir',
      'status': 'Agendado',
    },
    {
      'id': 'r16_7',
      'group': 'R16',
      'homeTeam': 'Vencedor R32',
      'homeFlag':
          'https://upload.wikimedia.org/wikipedia/commons/thumb/a/ad/Placeholder_no_text.svg/150px-Placeholder_no_text.svg.png',
      'awayTeam': 'Vencedor R32',
      'awayFlag':
          'https://upload.wikimedia.org/wikipedia/commons/thumb/a/ad/Placeholder_no_text.svg/150px-Placeholder_no_text.svg.png',
      'date': DateTime(2026, 7, 7, 13, 0),
      'stadium': 'A Definir',
      'country': 'A Definir',
      'location': 'A Definir',
      'status': 'Agendado',
    },
    {
      'id': 'r16_8',
      'group': 'R16',
      'homeTeam': 'Vencedor R32',
      'homeFlag':
          'https://upload.wikimedia.org/wikipedia/commons/thumb/a/ad/Placeholder_no_text.svg/150px-Placeholder_no_text.svg.png',
      'awayTeam': 'Vencedor R32',
      'awayFlag':
          'https://upload.wikimedia.org/wikipedia/commons/thumb/a/ad/Placeholder_no_text.svg/150px-Placeholder_no_text.svg.png',
      'date': DateTime(2026, 7, 7, 17, 0),
      'stadium': 'A Definir',
      'country': 'A Definir',
      'location': 'A Definir',
      'status': 'Agendado',
    },

    // ==========================================
    // === MATA-MATA: QUARTAS DE FINAL (4 jogos) ===
    // ==========================================
    {
      'id': 'qf_1',
      'group': 'QF',
      'homeTeam': 'Vencedor Oitavas',
      'homeFlag':
          'https://upload.wikimedia.org/wikipedia/commons/thumb/a/ad/Placeholder_no_text.svg/150px-Placeholder_no_text.svg.png',
      'awayTeam': 'Vencedor Oitavas',
      'awayFlag':
          'https://upload.wikimedia.org/wikipedia/commons/thumb/a/ad/Placeholder_no_text.svg/150px-Placeholder_no_text.svg.png',
      'date': DateTime(2026, 7, 9, 16, 0),
      'stadium': 'A Definir',
      'country': 'A Definir',
      'location': 'A Definir',
      'status': 'Agendado',
    },
    {
      'id': 'qf_2',
      'group': 'QF',
      'homeTeam': 'Vencedor Oitavas',
      'homeFlag':
          'https://upload.wikimedia.org/wikipedia/commons/thumb/a/ad/Placeholder_no_text.svg/150px-Placeholder_no_text.svg.png',
      'awayTeam': 'Vencedor Oitavas',
      'awayFlag':
          'https://upload.wikimedia.org/wikipedia/commons/thumb/a/ad/Placeholder_no_text.svg/150px-Placeholder_no_text.svg.png',
      'date': DateTime(2026, 7, 10, 16, 0),
      'stadium': 'A Definir',
      'country': 'A Definir',
      'location': 'A Definir',
      'status': 'Agendado',
    },
    {
      'id': 'qf_3',
      'group': 'QF',
      'homeTeam': 'Vencedor Oitavas',
      'homeFlag':
          'https://upload.wikimedia.org/wikipedia/commons/thumb/a/ad/Placeholder_no_text.svg/150px-Placeholder_no_text.svg.png',
      'awayTeam': 'Vencedor Oitavas',
      'awayFlag':
          'https://upload.wikimedia.org/wikipedia/commons/thumb/a/ad/Placeholder_no_text.svg/150px-Placeholder_no_text.svg.png',
      'date': DateTime(2026, 7, 11, 16, 0),
      'stadium': 'A Definir',
      'country': 'A Definir',
      'location': 'A Definir',
      'status': 'Agendado',
    },
    {
      'id': 'qf_4',
      'group': 'QF',
      'homeTeam': 'Vencedor Oitavas',
      'homeFlag':
          'https://upload.wikimedia.org/wikipedia/commons/thumb/a/ad/Placeholder_no_text.svg/150px-Placeholder_no_text.svg.png',
      'awayTeam': 'Vencedor Oitavas',
      'awayFlag':
          'https://upload.wikimedia.org/wikipedia/commons/thumb/a/ad/Placeholder_no_text.svg/150px-Placeholder_no_text.svg.png',
      'date': DateTime(2026, 7, 11, 20, 0),
      'stadium': 'A Definir',
      'country': 'A Definir',
      'location': 'A Definir',
      'status': 'Agendado',
    },

    // ==========================================
    // === MATA-MATA: SEMIFINAL (2 jogos) ===
    // ==========================================
    {
      'id': 'sf_1',
      'group': 'SF',
      'homeTeam': 'Vencedor Quartas',
      'homeFlag':
          'https://upload.wikimedia.org/wikipedia/commons/thumb/a/ad/Placeholder_no_text.svg/150px-Placeholder_no_text.svg.png',
      'awayTeam': 'Vencedor Quartas',
      'awayFlag':
          'https://upload.wikimedia.org/wikipedia/commons/thumb/a/ad/Placeholder_no_text.svg/150px-Placeholder_no_text.svg.png',
      'date': DateTime(2026, 7, 14, 16, 0),
      'stadium': 'A Definir',
      'country': 'A Definir',
      'location': 'A Definir',
      'status': 'Agendado',
    },
    {
      'id': 'sf_2',
      'group': 'SF',
      'homeTeam': 'Vencedor Quartas',
      'homeFlag':
          'https://upload.wikimedia.org/wikipedia/commons/thumb/a/ad/Placeholder_no_text.svg/150px-Placeholder_no_text.svg.png',
      'awayTeam': 'Vencedor Quartas',
      'awayFlag':
          'https://upload.wikimedia.org/wikipedia/commons/thumb/a/ad/Placeholder_no_text.svg/150px-Placeholder_no_text.svg.png',
      'date': DateTime(2026, 7, 15, 16, 0),
      'stadium': 'A Definir',
      'country': 'A Definir',
      'location': 'A Definir',
      'status': 'Agendado',
    },

    // ==========================================
    // === MATA-MATA: FINAL (1 jogo) ===
    // ==========================================
    {
      'id': 'final_1',
      'group': 'FINAL',
      'homeTeam': 'Vencedor Semi 1',
      'homeFlag':
          'https://upload.wikimedia.org/wikipedia/commons/thumb/a/ad/Placeholder_no_text.svg/150px-Placeholder_no_text.svg.png',
      'awayTeam': 'Vencedor Semi 2',
      'awayFlag':
          'https://upload.wikimedia.org/wikipedia/commons/thumb/a/ad/Placeholder_no_text.svg/150px-Placeholder_no_text.svg.png',
      'date': DateTime(2026, 7, 19, 16, 0),
      'stadium': 'MetLife Estádio',
      'country': 'Estados Unidos',
      'location': 'Now York',
      'status': 'Agendado',
    },
  ];

  // print('⏳ Enviando grupos oficias para o Firebase...');

  for (var jogo in jogos) {
    await collection.doc(jogo['id'] as String).set({
      'id': jogo['id'],
      'group': jogo['group'],
      'homeTeam': jogo['homeTeam'],
      'homeFlag': jogo['homeFlag'],
      'awayTeam': jogo['awayTeam'],
      'awayFlag': jogo['awayFlag'],
      'date': Timestamp.fromDate(jogo['date'] as DateTime),
      'stadium': jogo['stadium'],
      'country': jogo['country'],
      'location': jogo['location'],
      'status': jogo['status'],
    });
  }
  // print('🔥 GRUPOS POPULADOS COM SUCESSO!');
}
